name: wf-ci-develop
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
jobs:
  lint-develop-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository On the Runner
        uses: actions/checkout@v4
      - name: Lint HTML Files with HTMLHint
        run: npx htmlhint "**/*.html"
      - name: Lint CSS Files with Stylelint
        run: npx stylelint "**/*.css"
      - name: Build website with Parcel
        run: npx parcel build "./stc/index.html" --dist-dir "./dist"
     
